# Copyright (c) 2022 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU General Public License version 3.0 or later

name: Detect outdated pre-commit hooks

on:
  schedule:
    - cron: '0 16 * * 5'  # Every Friday 4pm

jobs:
  pip_detect_outdated:
    name: Detect outdated pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Set up Python 3.9
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.9

      - name: Install pre-commit
        run: |-
          pip install \
            --disable-pip-version-check \
            --no-warn-script-location \
            --user \
            pre-commit
          echo "PATH=${HOME}/.local/bin:${PATH}" >> "${GITHUB_ENV}"

      - name: Check for outdated hooks
        run: |-
          pre-commit autoupdate
          git diff -- .pre-commit-config.yaml

      - name: Create pull request from changes (if any)
        id: create-pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          author: 'pre-commit <pre-commit@tools.invalid>'
          base: master
          body: "For your consideration :smiley:"
          branch: precommit-autoupdate
          commit-message: "pre-commit: Autoupdate"
          delete-branch: true
          labels: enhancement
          title: "pre-commit: Autoupdate"

      - name: Log pull request URL
        run: |
          echo "Pull Request URL is: ${{ steps.create-pull-request.outputs.pull-request-url }}"
